# Generated by Django 4.2 on 2023-04-26 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'CSV Task', 'verbose_name_plural': 'CSV Tasks'},
        ),
        migrations.RemoveField(
            model_name='csvtask',
            name='user',
        ),
        migrations.AlterField(
            model_name='csvtask',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to='media/csv_files', validators=[django.core.validators.FileExtensionValidator(['csv', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='csvtask',
            name='file',
            field=models.FileField(upload_to='media/csv_files', validators=[django.core.validators.FileExtensionValidator(['csv', 'txt'])]),
        ),
    ]
