# Generated by Django 4.2 on 2023-04-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_api', '0003_remove_csvtask_converted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvtask',
            name='status',
            field=models.CharField(default='PENDING', max_length=15),
        ),
    ]
